### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by thisrod** [thisrod/Superfluids.jl#1]
- [ ] Default macros
- [ ] Specify `steady_lattice`
- [ ] Update docstrings
- [ ] Write README
- [ ] Write up how vortex constraints work
- [ ] Finish manual

Lower order issues:

- [ ] Polar spectral methods
